### ISSUE TITLE
Trying to attack party members

### ISSUE THREAD

**Issue by rrbailey89** [akira0245/Kombatant#6]
not sure if its magitek, rebornbuddy or if its kombatant but when playing as a healer if I manually select a party member I see in RB that magitek is trying to attack the party member selected

**Comment by rrbailey89** [comment]
I can confirm that this is an issue with kombatant. When on WHM it is trying to attack other players, npcs, etc when selected. When using ATB this is not an issue.

**Comment by akira0245** [comment]
No this is not a kombatant issue. 
During combat, kombatant will execute CR's `Heal`, `CombatBuff` and `Combat` behavior in order, regardless of current selected target. Kombatant doesn't have direct control on which character CR chooses to heal or attack, and it's not wise to do so. For example, if the botbase skips executing combat behavior when the current target is a party member, then all combat code in CR will not be executed (such as use AOE spells among enemies). CR should take responsibility for determining whether to attack current target itself instead of letting Botbase make that decision.

**Comment by rrbailey89** [comment]
> No this is not a kombatant issue. During combat, kombatant will execute CR's `Heal`, `CombatBuff` and `Combat` behavior in order, regardless of current selected target. Kombatant doesn't have direct control on which character CR chooses to heal or attack, and it's not wise to do so. For example, if the botbase skips executing combat behavior when the current target is a party member, then all combat code in CR will not be executed (such as use AOE spells among enemies). CR should take responsibility for determining whether to attack current target itself instead of letting Botbase make that decision.

This is odd to me, because it does not happen with ATB as the BotBase and Magitek as the CR... only Kombatant and Magitek.

see the video attached. 


see the video attached. see the video attached. 

https://github.com/akira0245/Kombatant/assets/6540217/6f16e932-7dd2-4d20-b8d7-b46cd089ba3c

**Comment by akira0245** [comment]
Magitek has added check on it's pull behavior. Closing this issue now.
